name = "kalawa-website"
compatibility_date = "2024-10-01"
pages_build_output_dir = "."

[build]
command = "echo 'No build step needed for static site'"
cwd = "."
watch_dir = "."

[env.production]
name = "kalawa-website"

[env.preview]
name = "kalawa-website-preview"